// This file is generated automatically by Next.js
// Do not edit this file manually

type AppRoutes = "/" | "/analytics" | "/campaigns" | "/connections" | "/contacts" | "/join/[slug]" | "/messages"
type AppRouteHandlerRoutes = "/api/auth/[...nextauth]" | "/api/campaigns/[campaignId]/draw-winner" | "/api/campaigns/[campaignId]/live" | "/api/campaigns/[campaignId]/settings" | "/api/campaigns/[campaignId]/templates" | "/api/connections" | "/api/connections/[connectionId]/connect" | "/api/connections/[connectionId]/status" | "/api/google/connect" | "/api/public/[slug]" | "/api/uploads/media"
type PageRoutes = never
type LayoutRoutes = "/"
type RedirectRoutes = never
type RewriteRoutes = never
type Routes = AppRoutes | PageRoutes | LayoutRoutes | RedirectRoutes | RewriteRoutes | AppRouteHandlerRoutes


interface ParamMap {
  "/": {}
  "/analytics": {}
  "/api/auth/[...nextauth]": { "nextauth": string[]; }
  "/api/campaigns/[campaignId]/draw-winner": { "campaignId": string; }
  "/api/campaigns/[campaignId]/live": { "campaignId": string; }
  "/api/campaigns/[campaignId]/settings": { "campaignId": string; }
  "/api/campaigns/[campaignId]/templates": { "campaignId": string; }
  "/api/connections": {}
  "/api/connections/[connectionId]/connect": { "connectionId": string; }
  "/api/connections/[connectionId]/status": { "connectionId": string; }
  "/api/google/connect": {}
  "/api/public/[slug]": { "slug": string; }
  "/api/uploads/media": {}
  "/campaigns": {}
  "/connections": {}
  "/contacts": {}
  "/join/[slug]": { "slug": string; }
  "/messages": {}
}


export type ParamsOf<Route extends Routes> = ParamMap[Route]

interface LayoutSlotMap {
  "/": never
}


export type { AppRoutes, PageRoutes, LayoutRoutes, RedirectRoutes, RewriteRoutes, ParamMap, AppRouteHandlerRoutes }

declare global {
  /**
   * Props for Next.js App Router page components
   * @example
   * ```tsx
   * export default function Page(props: PageProps<'/blog/[slug]'>) {
   *   const { slug } = await props.params
   *   return <div>Blog post: {slug}</div>
   * }
   * ```
   */
  interface PageProps<AppRoute extends AppRoutes> {
    params: Promise<ParamMap[AppRoute]>
    searchParams: Promise<Record<string, string | string[] | undefined>>
  }

  /**
   * Props for Next.js App Router layout components
   * @example
   * ```tsx
   * export default function Layout(props: LayoutProps<'/dashboard'>) {
   *   return <div>{props.children}</div>
   * }
   * ```
   */
  type LayoutProps<LayoutRoute extends LayoutRoutes> = {
    params: Promise<ParamMap[LayoutRoute]>
    children: React.ReactNode
  } & {
    [K in LayoutSlotMap[LayoutRoute]]: React.ReactNode
  }

  /**
   * Context for Next.js App Router route handlers
   * @example
   * ```tsx
   * export async function GET(request: NextRequest, context: RouteContext<'/api/users/[id]'>) {
   *   const { id } = await context.params
   *   return Response.json({ id })
   * }
   * ```
   */
  interface RouteContext<AppRouteHandlerRoute extends AppRouteHandlerRoutes> {
    params: Promise<ParamMap[AppRouteHandlerRoute]>
  }
}
